### PR TITLE
RGB22: Decentralized identity

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Review by cryptoquick — APPROVED** [review]
This all looks great! I'd love to see something like Keybase for something like this, and it has all the features for how I'd imagine this to work.

Also, I think it'd also work very well with a use-case we want to support at DIBA, for artist profiles that can be associated with RGB21. Can you think of a good way to associate an RGB21 NFT with an RGB22 DID?

Also, just for clarity, is there a way public contract data can be revealed, possibly to the public so it's posted on a website, without revealing any of the blinding factors behind the seals? Does this exist already for RGB20 or will it need to be built?

**Comment by dr-orlovsky** [comment]
> Also, I think it'd also work very well with a use-case we want to support at DIBA, for artist profiles that can be associated with RGB21. Can you think of a good way to associate an RGB21 NFT with an RGB22 DID?

I think the association has to be done outside of RGB -- by providing a signature over NFT with an identity key. Wallets which support both RGB21 and RGB22 than can lookup the key among known RGB22 identities and associate NFT with that artist.

For signing RGB contracts I am thinking about adding signature to `Contract` type of consignment in RGB stdlib. It won't be necessary RGB22 signature, but it can be any signature (including PGP based ones).

> Also, just for clarity, is there a way public contract data can be revealed

I have no idea what you call "public contract data", so can't answer :)

**Comment by cryptoquick** [comment]
> > Also, I think it'd also work very well with a use-case we want to support at DIBA, for artist profiles that can be associated with RGB21. Can you think of a good way to associate an RGB21 NFT with an RGB22 DID?
> 
> I think the association has to be done outside of RGB -- by providing a signature over NFT with an identity key. Wallets which support both RGB21 and RGB22 than can lookup the key among known RGB22 identities and associate NFT with that artist.
> 
> For signing RGB contracts I am thinking about adding signature to `Contract` type of consignment in RGB stdlib. It won't be necessary RGB22 signature, but it can be any signature (including PGP based ones).

Sure, so a consignment could be signed by the same key published in an RGB22 DID and the signature provided alongside the consignment? Would this be signing a hash of the consignment or an id pertinent to the contents? Would this be done for transfer consignments in addition to contract consignments?

> > Also, just for clarity, is there a way public contract data can be revealed
> 
> I have no idea what you call "public contract data", so can't answer :)

This would be data needed to prove the veracity of the identity, such as public keys and signatures, without sharing on-chain outputs or blinding factors. Is such a thing possible?

**Comment by dr-orlovsky** [comment]
> Sure, so a consignment could be signed by the same key published in an RGB22 DID and the signature provided alongside the consignment?

Yes

> Would this be signing a hash of the consignment or an id pertinent to the contents?
> Would this be done for transfer consignments in addition to contract consignments?

The signatures are only needed for genesis, by the genesis hash (which is the contract id). It may be present in both contract and transfer consignments.

> This would be data needed to prove the veracity of the identity, such as public keys and signatures, without sharing on-chain outputs or blinding factors. Is such a thing possible?

I am still struggling to understand the question.

If you are asking would RGB22-based identities expose revocation seals such that anybody can ensure that the key was not revoked, the answer is:

this will work the same way as for any other RGB contract, including fungible tokens. If somebody will provide a consignment hiding single-use-seals involved in validating certain things, this consignment would fail to validate. It will be up to the published to ensure that all required information is present in the revealed (and not concealed) form, otherwise nobody will accept it.

**Comment by cryptoquick** [comment]
That makes sense, thank you.

**Pull request merged**
